# azure-pipelines.yml
trigger:
- main  # Change this to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  inputs:
    repository: 'self'
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Set up virtual environment and Install dependencies'

- script: |
    python -m pytest -v test_flow1.py
  displayName: 'Run tests'
